spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/dbcourse
    username: postgres
    password: project123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
  application:
    name: catalogos-service
  profiles:
    active: dev

server:
  port: 8090

eureka:
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8000/eureka
  instance:
    leaseRenewalIntervalInSeconds: 5
    preferIpAddress: true