spring:
  datasource:
    url: jdbc:postgresql://192.168.1.75:5432/dbcourse
    username: postgres
    password: project123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
  application:
    name: catalogos-service
  profiles:
    active: dev

server:
  port: 8090

